from tkinter import*
import customtkinter
from PIL import ImageTk, Image
from tkinter import ttk
import tkinter as tk

class page_books():
    
    def Books(self):
        # def on_scroll(*args):
        #     canvas.yview(*args)
            
        win1 = Tk()
        win1.title('Page1')
        

        # Add some content to the frame
                
        
        #****** scroll bar
        # main_frame = Frame(win1)
        # main_frame.pack(file=BOTH, expand=1)
        
        # my_canvas = Canvas(main_frame)
        # my_canvas.pack(side=LEFT, fill= BOTH, expand=1)
        
        # my_scrollbar = ttk.Scrollbar(main_frame, orient= VERTICAL, command=my_canvas.yview)
        # my_scrollbar.pack(side=RIGHT, filee=Y)
        
        # my_canvas.configure(yscrollcommand=my_scrollbar)
        # my_canvas.bind('<Configure>', lambda e: my_canvas.configure(scrollregion=my_canvas.bbox("all")))
        
        # second_frame = Frame(my_canvas)
        
        # my_canvas.create_window((0,0), window=second_frame, anchor="nw")
        
        def book4():
            win1.destroy()
            from book import book1

            
            
        imgage=ImageTk.PhotoImage(Image.open("images/img1.png"))
        lb=customtkinter.CTkLabel(win1,image=imgage)
        lb.pack()
        
        frame1=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame1.place(x= 20, y= 40)
        img_old = Image.open("img_book/adv1.jfif")
        width,height = img_old.size
        width_new =int(120)
        height_new =int(130)
        img_resize = img_old.resize((width_new,height_new))
        my_img = ImageTk.PhotoImage(img_resize)
        my0 = Label(frame1, image= my_img)
        my0.pack()
        my0.place(y=10, x=15)
        write0 = customtkinter.CTkLabel(frame1, text="Price : ", font=('Century Gothic',15, 'bold'))
        write0.place(x=33, y=144)
        writ0 = customtkinter.CTkLabel(frame1, text="10$", font=('Century Gothic',15, 'bold'))
        writ0.place(x=83, y=144)
        but0 = customtkinter.CTkButton(frame1, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but0.place(x=41, y=171)
        
        frame2=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame2.place(x= 250, y= 40)
        img_old1 = Image.open("img_book/Adv2.jfif")
        width,height = img_old1.size
        width_new1 =int(120)
        height_new1 =int(130)
        img_resize1 = img_old1.resize((width_new1,height_new1))
        my_img1 = ImageTk.PhotoImage(img_resize1)
        my1 = Label(frame2, image= my_img1)
        my1.pack()
        my1.place(y=10, x=15)
        write1 = customtkinter.CTkLabel(frame2, text="Price : ", font=('Century Gothic',15, 'bold'))
        write1.place(x=33, y=144)
        write2 = customtkinter.CTkLabel(frame2, text="15$", font=('Century Gothic',15, 'bold'))
        write2.place(x=83, y=144)
        but1 = customtkinter.CTkButton(frame2, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but1.place(x=41, y=171)
        
        frame3=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame3.place(x= 480, y= 40)
        img_old2 = Image.open("img_book/Adv3.jfif")
        width,height = img_old2.size
        width_new2 =int(120)
        height_new2 =int(130)
        img_resize2 = img_old2.resize((width_new2,height_new2))
        my_img2 = ImageTk.PhotoImage(img_resize2)
        my2 = Label(frame3, image= my_img2)
        my2.pack()
        my2.place(y=10, x=15)
        write2 = customtkinter.CTkLabel(frame3, text="Price : ", font=('Century Gothic',15, 'bold'))
        write2.place(x=33, y=144)
        write3 = customtkinter.CTkLabel(frame3, text="14$", font=('Century Gothic',15, 'bold'))
        write3.place(x=83, y=144)
        but2 = customtkinter.CTkButton(frame3, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but2.place(x=41, y=171)
        
        frame4=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame4.place(x= 710, y= 40)
        img_old3 = Image.open("img_book/img_6.jpg")
        width,height = img_old3.size
        width_new3 =int(120)
        height_new3 =int(130)
        img_resize3 = img_old3.resize((width_new3,height_new3))
        my_img3 = ImageTk.PhotoImage(img_resize3)
        my3 = Label(frame4, image= my_img3)
        my3.pack()
        my3.place(y=10, x=15)
        write3 = customtkinter.CTkLabel(frame4, text="Price : ", font=('Century Gothic',15, 'bold'))
        write3.place(x=33, y=144)
        write4 = customtkinter.CTkLabel(frame4, text="8$", font=('Century Gothic',15, 'bold'))
        write4.place(x=83, y=144)
        but4 = customtkinter.CTkButton(frame4, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'), command=book4)
        but4.place(x=41, y=171)
        
        frame5=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame5.place(x= 940, y= 40)
        img_old4 = Image.open("img_book/Adv5.jfif")
        width,height = img_old4.size
        width_new4 =int(120)
        height_new4 =int(130)
        img_resize4 = img_old4.resize((width_new4,height_new4))
        my_img4 = ImageTk.PhotoImage(img_resize4)
        my4 = Label(frame5, image= my_img4)
        my4.pack()
        my4.place(y=10, x=15)
        write4 = customtkinter.CTkLabel(frame5, text="Price : ", font=('Century Gothic',15, 'bold'))
        write4.place(x=33, y=144)
        write5 = customtkinter.CTkLabel(frame5, text="5$", font=('Century Gothic',15, 'bold'))
        write5.place(x=83, y=144)
        but5 = customtkinter.CTkButton(frame5, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but5.place(x=41, y=171)
        
        frame6=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame6.place(x= 1170, y= 40)
        img_old5 = Image.open("img_book/adv6.jfif")
        width,height = img_old5.size
        width_new5 =int(120)
        height_new5 =int(130)
        img_resize5 = img_old5.resize((width_new5,height_new5))
        my_img5 = ImageTk.PhotoImage(img_resize5)
        my5 = Label(frame6, image= my_img5)
        my5.pack()
        my5.place(y=10, x=15)
        write5 = customtkinter.CTkLabel(frame6, text="Price : ", font=('Century Gothic',15, 'bold'))
        write5.place(x=33, y=144)
        write6 = customtkinter.CTkLabel(frame6, text="20$", font=('Century Gothic',15, 'bold'))
        write6.place(x=83, y=144)
        but6 = customtkinter.CTkButton(frame6, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but6.place(x=41, y=171)
        
        frame7=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame7.place(x= 20, y= 270)
        img_old7 = Image.open("img_book/adv7.jfif")
        width,height = img_old7.size
        width_new7 =int(120)
        height_new7 =int(130)
        img_resize7 = img_old7.resize((width_new7,height_new7))
        my_img7 = ImageTk.PhotoImage(img_resize7)
        my7 = Label(frame7, image= my_img7)
        my7.pack()
        my7.place(y=10, x=15)
        write7 = customtkinter.CTkLabel(frame7, text="Price : ", font=('Century Gothic',15, 'bold'))
        write7.place(x=33, y=144)
        write7 = customtkinter.CTkLabel(frame7, text="3$", font=('Century Gothic',15, 'bold'))
        write7.place(x=83, y=144)
        but7 = customtkinter.CTkButton(frame7, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but7.place(x=41, y=171)
        
        frame8=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame8.place(x= 250, y= 270)
        img_old8 = Image.open("img_book/adv8.jfif")
        width,height = img_old8.size
        width_new8 =int(120)
        height_new8 =int(130)
        img_resize8 = img_old8.resize((width_new8,height_new8))
        my_img8 = ImageTk.PhotoImage(img_resize8)
        my8 = Label(frame8, image= my_img8)
        my8.pack()
        my8.place(y=10, x=15)
        write8 = customtkinter.CTkLabel(frame8, text="Price : ", font=('Century Gothic',15, 'bold'))
        write8.place(x=33, y=144)
        write8 = customtkinter.CTkLabel(frame8, text="4$", font=('Century Gothic',15, 'bold'))
        write8.place(x=83, y=144)
        but8 = customtkinter.CTkButton(frame8, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but8.place(x=41, y=171)
        
        frame9=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame9.place(x= 480, y= 270)
        img_old9 = Image.open("img_book/c1.jfif")
        width,height = img_old9.size
        width_new9 =int(120)
        height_new9 =int(130)
        img_resize9 = img_old9.resize((width_new9,height_new9))
        my_img9 = ImageTk.PhotoImage(img_resize9)
        my9 = Label(frame9, image= my_img9)
        my9.pack()
        my9.place(y=10, x=15)
        write9 = customtkinter.CTkLabel(frame9, text="Price : ", font=('Century Gothic',15, 'bold'))
        write9.place(x=33, y=144)
        write9 = customtkinter.CTkLabel(frame9, text="7$", font=('Century Gothic',15, 'bold'))
        write9.place(x=83, y=144)
        but9 = customtkinter.CTkButton(frame9, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but9.place(x=41, y=171)
        
        frame10=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame10.place(x= 710, y= 270)
        img_old10 = Image.open("img_book/c2.jfif")
        width,height = img_old10.size
        width_new10 =int(120)
        height_new10 =int(130)
        img_resize10 = img_old10.resize((width_new10,height_new10))
        my_img10 = ImageTk.PhotoImage(img_resize10)
        my10 = Label(frame10, image= my_img10)
        my10.pack()
        my10.place(y=10, x=15)
        write10 = customtkinter.CTkLabel(frame10, text="Price : ", font=('Century Gothic',15, 'bold'))
        write10.place(x=33, y=144)
        write10 = customtkinter.CTkLabel(frame10, text="2$", font=('Century Gothic',15, 'bold'))
        write10.place(x=83, y=144)
        but10 = customtkinter.CTkButton(frame10, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but10.place(x=41, y=171)
        
        frame11=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame11.place(x= 940, y= 270)
        img_old11 = Image.open("img_book/c3.jfif")
        width,height = img_old11.size
        width_new11 =int(120)
        height_new11 =int(130)
        img_resize11 = img_old11.resize((width_new11,height_new11))
        my_img11 = ImageTk.PhotoImage(img_resize11)
        my11 = Label(frame11, image= my_img11)
        my11.pack()
        my11.place(y=10, x=15)
        write11 = customtkinter.CTkLabel(frame11, text="Price : ", font=('Century Gothic',15, 'bold'))
        write11.place(x=33, y=144)
        write11 = customtkinter.CTkLabel(frame11, text="20$", font=('Century Gothic',15, 'bold'))
        write11.place(x=83, y=144)
        but11 = customtkinter.CTkButton(frame11, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but11.place(x=41, y=171)
    
        frame12=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame12.place(x= 1170, y= 270)
        img_old12 = Image.open("img_book/c4.jfif")
        width,height = img_old12.size
        width_new12 =int(120)
        height_new12 =int(130)
        img_resize12 = img_old12.resize((width_new12,height_new12))
        my_img12 = ImageTk.PhotoImage(img_resize12)
        my12 = Label(frame12, image= my_img12)
        my12.pack()
        my12.place(y=10, x=15)
        write12 = customtkinter.CTkLabel(frame12, text="Price : ", font=('Century Gothic',15, 'bold'))
        write12.place(x=33, y=144)
        write12 = customtkinter.CTkLabel(frame12, text="12$", font=('Century Gothic',15, 'bold'))
        write12.place(x=83, y=144)
        but12 = customtkinter.CTkButton(frame12, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but12.place(x=41, y=171)
        
        frame13=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame13.place(x= 20, y= 500)
        img_old13 = Image.open("img_book/c5.jfif")
        width,height = img_old13.size
        width_new13 =int(120)
        height_new13 =int(130)
        img_resize13 = img_old13.resize((width_new13,height_new13))
        my_img13 = ImageTk.PhotoImage(img_resize13)
        my13 = Label(frame13, image= my_img13)
        my13.pack()
        my13.place(y=10, x=15)
        write13 = customtkinter.CTkLabel(frame13, text="Price : ", font=('Century Gothic',15, 'bold'))
        write13.place(x=33, y=144)
        write13 = customtkinter.CTkLabel(frame13, text="15$", font=('Century Gothic',15, 'bold'))
        write13.place(x=83, y=144)
        but13 = customtkinter.CTkButton(frame13, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but13.place(x=41, y=171)
        
        frame14=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame14.place(x= 250, y= 500)
        img_old14 = Image.open("img_book/c6.jfif")
        width,height = img_old14.size
        width_new14 =int(120)
        height_new14 =int(130)
        img_resize14 = img_old14.resize((width_new14,height_new14))
        my_img14 = ImageTk.PhotoImage(img_resize14)
        my14 = Label(frame14, image= my_img14)
        my14.pack()
        my14.place(y=10, x=15)
        write14 = customtkinter.CTkLabel(frame14, text="Price : ", font=('Century Gothic',15, 'bold'))
        write14.place(x=33, y=144)
        write14 = customtkinter.CTkLabel(frame14, text="9$", font=('Century Gothic',15, 'bold'))
        write14.place(x=83, y=144)
        but14 = customtkinter.CTkButton(frame14, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but14.place(x=41, y=171)
        
        frame15=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame15.place(x= 480, y= 500)
        img_old15 = Image.open("img_book/c7.jfif")
        width,height = img_old15.size
        width_new15 =int(120)
        height_new15 =int(130)
        img_resize15 = img_old15.resize((width_new15,height_new15))
        my_img15 = ImageTk.PhotoImage(img_resize15)
        my15 = Label(frame15, image= my_img15)
        my15.pack()
        my15.place(y=10, x=15)
        write15 = customtkinter.CTkLabel(frame15, text="Price : ", font=('Century Gothic',15, 'bold'))
        write15.place(x=33, y=144)
        write15 = customtkinter.CTkLabel(frame15, text="22$", font=('Century Gothic',15, 'bold'))
        write15.place(x=83, y=144)
        but15 = customtkinter.CTkButton(frame15, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but15.place(x=41, y=171)
        
        frame16=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame16.place(x= 710, y= 500)
        img_old16 = Image.open("img_book/c8.jfif")
        width,height = img_old16.size
        width_new16 =int(120)
        height_new16 =int(130)
        img_resize16 = img_old16.resize((width_new16,height_new16))
        my_img16 = ImageTk.PhotoImage(img_resize16)
        my16 = Label(frame16, image= my_img16)
        my16.pack()
        my16.place(y=10, x=15)
        write16 = customtkinter.CTkLabel(frame16, text="Price : ", font=('Century Gothic',15, 'bold'))
        write16.place(x=33, y=144)
        write16 = customtkinter.CTkLabel(frame16, text="3$", font=('Century Gothic',15, 'bold'))
        write16.place(x=83, y=144)
        but16 = customtkinter.CTkButton(frame16, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but16.place(x=41, y=171)
        
        frame17=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame17.place(x= 940, y= 500)
        img_old17 = Image.open("img_book/img_2.jpg")
        width,height = img_old17.size
        width_new17 =int(120)
        height_new17 =int(130)
        img_resize17 = img_old17.resize((width_new17,height_new17))
        my_img17 = ImageTk.PhotoImage(img_resize17)
        my17 = Label(frame17, image= my_img17)
        my17.pack()
        my17.place(y=10, x=15)
        write17 = customtkinter.CTkLabel(frame17, text="Price : ", font=('Century Gothic',15, 'bold'))
        write17.place(x=33, y=144)
        write17 = customtkinter.CTkLabel(frame17, text="15$", font=('Century Gothic',15, 'bold'))
        write17.place(x=83, y=144)
        but17 = customtkinter.CTkButton(frame17, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but17.place(x=41, y=171)
        
        frame18=customtkinter.CTkFrame(lb, width=150, height=200, corner_radius=15)
        frame18.place(x= 1170, y= 500)
        img_old18 = Image.open("img_book/img_3.jpeg")
        width,height = img_old18.size
        width_new18 =int(120)
        height_new18 =int(130)
        img_resize18 = img_old18.resize((width_new18,height_new18))
        my_img18 = ImageTk.PhotoImage(img_resize18)
        my18 = Label(frame18, image= my_img18)
        my18.pack()
        my18.place(y=10, x=15)
        write18 = customtkinter.CTkLabel(frame18, text="Price : ", font=('Century Gothic',15, 'bold'))
        write18.place(x=33, y=144)
        write18 = customtkinter.CTkLabel(frame18, text="12$", font=('Century Gothic',15, 'bold'))
        write18.place(x=83, y=144)
        but18 = customtkinter.CTkButton(frame18, text="Buy",height=7, width=65,font=('Century Gothic',15, 'bold'))
        but18.place(x=41, y=171)
        
        win1.state("zoomed")
        win1.mainloop()
book1 = page_books()
book1.Books()